create table t_contact (
  id                            bigint generated by default as identity (start with 1)  not null,
  name                          varchar(50),
  customer_id                   bigint not null,
  version                       bigint not null,
  created                       timestamp not null,
  updated                       timestamp not null,
  constraint pk_t_contact primary key (id)
);

create table t_customer (
  id                            bigint generated by default as identity (start with 1)  not null,
  name                          varchar(50),
  version                       bigint not null,
  created                       timestamp not null,
  updated                       timestamp not null,
  constraint pk_t_customer primary key (id)
);

alter table t_contact add constraint fk_t_contact_customer_id foreign key (customer_id) references t_customer (id) on delete restrict on update restrict;
create index ix_t_contact_customer_id on t_contact (customer_id);

